apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: bc-chuck-api-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    namespace: ${APP_PROJECT}
    name: "chuck-api"
  spec:
    tags:
    - from:
        kind: DockerImage
        name: "docker-registry.default.svc:5000/chuck/api"
      name: "latest"
      importPolicy:
        scheduled: true
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "chuck-api-int"
    namespace: ${OPS_PROJECT}
  spec:
    runPolicy: "Serial"
    source:
      git:
        uri: "https://github.com/Dimss/chuck-api"
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "openjdk-11-rhel7:latest"
    output:
      to:
        kind: "ImageStreamTag"
        name: "chuck-api:latest"
        namespace: ${APP_PROJECT}
parameters:
- description: App project
  name: APP_PROJECT
  required: true
- description: Ops project
  name: OPS_PROJECT
  required: true