apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: bc-chuck-api-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "chuck-api"
  spec:
    tags:
    - from:
        kind: DockerImage
        name: "docker-registry.default.svc:5000/chuck/api"
      name: "latest"
      importPolicy:
        scheduled: true
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "chuck-api"
  spec:
    runPolicy: "Serial"
    source:
      git:
        uri: "https://github.com/Dimss/chuck-api"
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "java:latest"
          namespace: openshift
    output:
      to:
        kind: "ImageStreamTag"
        name: "chuck-api:latest"