kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "chuck-api-base"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/chuck-api"
  strategy:
    customStrategy:
      from:
        kind: "DockerImage"
        name: "dimssss/custom-builder:0.20"
      secrets:
      - secretSource:
          name: "builder-config"
        mountPath: "/tmp/builder-config"
      env:
        - name: "OPS_TYPE"
          value: "build"
  triggers:
  - github:
      secret: dGvu1slX2WybtV_HOcYJ
    type: "GitHub"





